[project]
name = "ncdio-proxr"
version = "0.1.0"
description = "library for controlling NCD-IO ProXR relay controller"
requires-python = ">=3.8"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["ncd_io"]